import { EndpointDefinition, EndpointGroupMeta, EndpointParam } from './types';

// ============================================================
// ENDPOINT GROUPS
// ============================================================
export const ENDPOINT_GROUPS: EndpointGroupMeta[] = [
  {
    id: 'image-generation',
    label: 'Image Generation',
    icon: '🖼️',
    description: 'Text-to-Image, Image-to-Image',
  },
  {
    id: 'video-generation',
    label: 'Video Generation',
    icon: '🎬',
    description: 'Text-to-Video, Image-to-Video, Video Replace',
  },
  {
    id: 'audio-generation',
    label: 'Audio / TTS',
    icon: '🔊',
    description: 'Text-to-Speech',
  },
  {
    id: 'music-generation',
    label: 'Music Generation',
    icon: '🎵',
    description: 'Text-to-Music',
  },
  {
    id: 'transcription',
    label: 'Transcription',
    icon: '📝',
    description: 'Video/Audio to Text (Whisper)',
  },
  {
    id: 'ocr',
    label: 'OCR',
    icon: '👁️',
    description: 'Image to Text extraction',
  },
  {
    id: 'image-utils',
    label: 'Image Utils',
    icon: '🔧',
    description: 'Background removal, upscaling',
  },
  {
    id: 'embeddings',
    label: 'Embeddings',
    icon: '🧮',
    description: 'Text to vector embeddings',
  },
  {
    id: 'utility',
    label: 'Utility',
    icon: '⚙️',
    description: 'Balance, models, job results',
  },
];

// ============================================================
// SHARED PARAM BUILDERS (DRY helpers)
// ============================================================
// NOTE: These define form STRUCTURE only.
// Actual values (options, min/max, defaults) come from /models API
// and are applied dynamically in EndpointForm.

const promptParam = (required = true): EndpointParam => ({
  name: 'prompt',
  label: 'Prompt',
  type: 'textarea',
  required,
  placeholder: 'Describe what you want to generate...',
  description: 'Text description of desired output',
});

const negativePromptParam = (): EndpointParam => ({
  name: 'negative_prompt',
  label: 'Negative Prompt',
  type: 'textarea',
  required: false,
  placeholder: 'What to avoid in the output...',
  description: 'Text describing what to exclude',
});

const modelSelectParam = (): EndpointParam => ({
  name: 'model',
  label: 'Model',
  type: 'select',
  required: true,
  description: 'AI model to use for generation',
});

const seedParam = (): EndpointParam => ({
  name: 'seed',
  label: 'Seed',
  type: 'number',
  required: false,
  nullable: true,
  default: Math.floor(Math.random() * 1000000),
  placeholder: 'Random seed for reproducibility',
  description: 'Seed for reproducible results',
});

const stepsParam = (): EndpointParam => ({
  name: 'steps',
  label: 'Steps',
  type: 'number',
  required: false,
  nullable: true,
  description: 'Inference steps. Higher = better quality, slower.',
});

const guidanceParam = (): EndpointParam => ({
  name: 'guidance',
  label: 'Guidance Scale',
  type: 'number',
  required: false,
  nullable: true,
  step: 0.5,
  description: 'How closely to follow the prompt. Higher = more literal.',
});

const widthParam = (): EndpointParam => ({
  name: 'width',
  label: 'Width',
  type: 'number',
  required: false,
  nullable: true,
  description: 'Output width in pixels',
});

const heightParam = (): EndpointParam => ({
  name: 'height',
  label: 'Height',
  type: 'number',
  required: false,
  nullable: true,
  description: 'Output height in pixels',
});

const lorasParam = (): EndpointParam => ({
  name: 'loras',
  label: 'LoRA Adapters',
  type: 'lora-array',
  required: false,
  description: 'Array of LoRA adapters [{name, weight}]. Leave empty if not using.',
});

// ============================================================
// ENDPOINT DEFINITIONS
// ============================================================

export const ENDPOINTS: EndpointDefinition[] = [
  // ── Image Generation ──────────────────────────────────────
  {
    id: 'txt2img',
    name: 'Text to Image',
    group: 'image-generation',
    method: 'POST',
    path: '/txt2img',
    description: 'Generate image from text prompt',
    contentType: 'json',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/txt2img/price-calculation',
    params: [
      promptParam(),
      negativePromptParam(),
      modelSelectParam(),
      widthParam(),
      heightParam(),
      guidanceParam(),
      stepsParam(),
      seedParam(),
      lorasParam(),
    ],
  },

  {
    id: 'img2img',
    name: 'Image to Image',
    group: 'image-generation',
    method: 'POST',
    path: '/img2img',
    description: 'Edit/transform image using AI',
    contentType: 'multipart',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/img2img/price-calculation',
    params: [
      {
        name: 'image',
        label: 'Input Image',
        type: 'file',
        required: true,
        accept: 'image/*',
        multiple: true,
        multiFieldName: 'images[]',
        description: 'Single image (image) or multiple images (images[] array)',
      },
      promptParam(),
      modelSelectParam(),
      widthParam(),
      heightParam(),
      guidanceParam(),
      stepsParam(),
      seedParam(),
      lorasParam(),
    ],
  },

  // ── Video Generation ──────────────────────────────────────
  {
    id: 'img2video',
    name: 'Image to Video',
    group: 'video-generation',
    method: 'POST',
    path: '/img2video',
    description: 'Animate static image into video',
    contentType: 'multipart',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/img2video/price-calculation',
    params: [
      {
        name: 'first_frame_image',
        label: 'First Frame Image',
        type: 'file',
        required: true,
        accept: 'image/*',
        description: 'Starting frame image',
      },
      {
        name: 'last_frame_image',
        label: 'Last Frame Image',
        type: 'file',
        required: false,
        accept: 'image/*',
        description: 'Optional ending frame image',
      },
      promptParam(),
      negativePromptParam(),
      modelSelectParam(),
      widthParam(),
      heightParam(),
      guidanceParam(),
      stepsParam(),
      {
        name: 'frames',
        label: 'Frames',
        type: 'number',
        required: false,
        nullable: true,
        description: 'Number of frames to generate',
      },
      {
        name: 'fps',
        label: 'FPS',
        type: 'number',
        required: false,
        nullable: true,
        description: 'Frames per second',
      },
      seedParam(),
    ],
  },

  {
    id: 'audio2video',
    name: 'Audio to Video',
    group: 'video-generation',
    method: 'POST',
    path: '/aud2video',
    description: 'Generate video from audio',
    contentType: 'multipart',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/aud2video/price-calculation',
    params: [
      promptParam(),
      negativePromptParam(),
      {
        name: 'audio',
        label: 'Audio File',
        type: 'file',
        required: true,
        accept: 'audio/*,.mp3,.wav,.ogg,.flac',
        description: 'Audio to condition the video (mp3/wav/ogg/flac, max 20MB)',
      },
      {
        name: 'first_frame_image',
        label: 'First Frame Image',
        type: 'file',
        required: false,
        accept: 'image/*',
        description: 'Optional starting frame image',
      },
      {
        name: 'last_frame_image',
        label: 'Last Frame Image',
        type: 'file',
        required: false,
        accept: 'image/*',
        description: 'Optional ending frame image',
      },
      modelSelectParam(),
      widthParam(),
      heightParam(),
      guidanceParam(),
      stepsParam(),
      {
        name: 'frames',
        label: 'Frames',
        type: 'number',
        required: false,
        nullable: true,
        description: 'Number of frames to generate',
      },
      {
        name: 'fps',
        label: 'FPS',
        type: 'number',
        required: false,
        nullable: true,
        description: 'Frames per second',
      },
      seedParam(),
    ],
  },

  {
    id: 'txt2video',
    name: 'Text to Video',
    group: 'video-generation',
    method: 'POST',
    path: '/txt2video',
    description: 'Generate video from text description',
    contentType: 'json',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/txt2video/price-calculation',
    params: [
      promptParam(),
      negativePromptParam(),
      modelSelectParam(),
      widthParam(),
      heightParam(),
      guidanceParam(),
      stepsParam(),
      {
        name: 'frames',
        label: 'Frames',
        type: 'number',
        required: false,
        nullable: true,
        description: 'Number of frames to generate',
      },
      {
        name: 'fps',
        label: 'FPS',
        type: 'number',
        required: false,
        nullable: true,
        description: 'Frames per second',
      },
      seedParam(),
    ],
  },

  {
    id: 'video-replace',
    name: 'Video Replace',
    group: 'video-generation',
    method: 'POST',
    path: '/videos/replace',
    description: 'Replace a person in video with character from reference image',
    contentType: 'multipart',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/videos/replace/price',
    params: [
      {
        name: 'video',
        label: 'Input Video',
        type: 'file',
        required: true,
        accept: 'video/*,.mp4,.mpeg,.mov,.avi,.wmv,.ogg',
        description: 'Input video file (MP4, MPEG, QuickTime, AVI, WMV, OGG)',
      },
      {
        name: 'ref_image',
        label: 'Reference Image',
        type: 'file',
        required: true,
        accept: 'image/*',
        description: 'Reference character image (JPG, PNG, GIF, BMP, WebP, max 10MB)',
      },
      promptParam(false),
      modelSelectParam(),
      widthParam(),
      heightParam(),
      stepsParam(),
      seedParam(),
    ],
  },

  // ── Audio / TTS ───────────────────────────────────────────
  {
    id: 'txt2audio',
    name: 'Text to Speech',
    group: 'audio-generation',
    method: 'POST',
    path: '/txt2audio',
    description: 'Convert text to natural speech',
    contentType: 'multipart',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/txt2audio/price-calculation',
    params: [
      {
        name: 'text',
        label: 'Text',
        type: 'textarea',
        required: true,
        placeholder: 'Text to convert to speech...',
      },
      {
        name: 'instruct',
        label: 'Instruct',
        type: 'textarea',
        required: false,
        placeholder: 'A young female voice, clear and warm',
        description: 'Voice description (voice_design) or style control (custom_voice)',
        visibleWhen: { field: 'mode', values: ['voice_design', 'custom_voice'], matchEmpty: true },
      },
      {
        name: 'ref_audio',
        label: 'Reference Audio',
        type: 'file',
        required: false,
        accept: 'audio/*,.mp3,.wav,.flac,.ogg,.m4a',
        description: 'Reference audio for voice cloning (mp3/wav/flac/ogg/m4a, max 10MB, 3-10s)',
        visibleWhen: { field: 'mode', values: ['voice_clone'] },
      },
      {
        name: 'ref_text',
        label: 'Reference Text',
        type: 'textarea',
        required: false,
        placeholder: 'Transcript of reference audio...',
        description: 'Transcript of ref audio for improved cloning accuracy',
        visibleWhen: { field: 'mode', values: ['voice_clone'] },
      },
      modelSelectParam(),
      {
        name: 'mode',
        label: 'Mode',
        type: 'select',
        required: false,
        nullable: true,
        options: [
          { value: 'custom_voice', label: 'Custom Voice' },
          { value: 'voice_clone', label: 'Voice Clone' },
          { value: 'voice_design', label: 'Voice Design' },
        ],
        description: 'TTS mode. Null = model default.',
      },
      {
        name: 'voice',
        label: 'Voice',
        type: 'select',
        required: false,
        nullable: true,
        description: 'Voice to use (custom_voice mode)',
        visibleWhen: { field: 'mode', values: ['custom_voice'], matchEmpty: true },
      },
      {
        name: 'lang',
        label: 'Language',
        type: 'select',
        required: true,
        description: 'Language for TTS',
      },
      {
        name: 'format',
        label: 'Format',
        type: 'select',
        required: false,
        nullable: true,
        options: [
          { value: 'mp3', label: 'MP3' },
          { value: 'wav', label: 'WAV' },
          { value: 'flac', label: 'FLAC' },
        ],
      },
      {
        name: 'speed',
        label: 'Speed',
        type: 'number',
        required: false,
        nullable: true,
        step: 0.1,
        description: 'Speech speed multiplier',
      },
      {
        name: 'sample_rate',
        label: 'Sample Rate',
        type: 'number',
        required: false,
        nullable: true,
        description: 'Audio sample rate in Hz',
      },
    ],
  },

  // ── Music Generation ────────────────────────────────────
  {
    id: 'txt2music',
    name: 'Text to Music',
    group: 'music-generation',
    method: 'POST',
    path: '/txt2music',
    description: 'Generate music from text description',
    contentType: 'multipart',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/txt2music/price-calculation',
    params: [
      {
        name: 'caption',
        label: 'Caption',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the music (e.g. "upbeat pop song with electric guitar")',
        description: 'Music style and mood description',
      },
      {
        name: 'lyrics',
        label: 'Lyrics',
        type: 'textarea',
        required: false,
        nullable: true,
        default: '[Instrumental]',
        placeholder: '[verse]\nLyrics here...\n[chorus]\nChorus here...',
        description: 'Song lyrics or [Instrumental] for instrumental-only',
      },
      modelSelectParam(),
      {
        name: 'duration',
        label: 'Duration (s)',
        type: 'number',
        required: true,
        min: 10,
        max: 600,
        default: 30,
        description: 'Duration in seconds (10-600)',
      },
      {
        name: 'bpm',
        label: 'BPM',
        type: 'number',
        required: false,
        nullable: true,
        min: 30,
        max: 300,
        description: 'Beats per minute (empty for auto)',
      },
      {
        name: 'keyscale',
        label: 'Key / Scale',
        type: 'text',
        required: false,
        nullable: true,
        placeholder: 'C major',
        description: 'Musical key (e.g. "C major", "F# minor")',
      },
      {
        name: 'timesignature',
        label: 'Time Signature',
        type: 'select',
        required: false,
        nullable: true,
        valueType: 'number',
        options: [
          { value: '2', label: '2/4' },
          { value: '3', label: '3/4' },
          { value: '4', label: '4/4' },
          { value: '6', label: '6/8' },
        ],
        description: 'Time signature (null for auto)',
      },
      {
        name: 'vocal_language',
        label: 'Vocal Language',
        type: 'text',
        required: false,
        nullable: true,
        default: 'en',
        placeholder: 'en',
        description: 'Language code for vocals',
      },
      {
        name: 'inference_steps',
        label: 'Steps',
        type: 'number',
        required: false,
        nullable: true,
        default: 8,
        min: 1,
        max: 100,
        description: '8 = turbo (fast), 32-100 = base (higher quality)',
      },
      {
        name: 'guidance_scale',
        label: 'Guidance Scale',
        type: 'number',
        required: false,
        nullable: true,
        default: 7.0,
        step: 0.5,
        min: 0,
        max: 20,
        description: 'How closely to follow the caption',
      },
      seedParam(),
      {
        name: 'format',
        label: 'Format',
        type: 'select',
        required: false,
        nullable: true,
        default: 'flac',
        options: [
          { value: 'wav', label: 'WAV' },
          { value: 'mp3', label: 'MP3' },
          { value: 'flac', label: 'FLAC' },
        ],
      },
      {
        name: 'reference_audio',
        label: 'Reference Audio',
        type: 'file',
        required: false,
        accept: 'audio/*,.mp3,.wav,.flac,.ogg,.m4a',
        description: 'Optional reference audio for style transfer (mp3/wav/flac/ogg/m4a, max 10MB)',
      },
    ],
  },

  // ── Transcription ─────────────────────────────────────────
  {
    id: 'vid2txt',
    name: 'Video URL to Text',
    group: 'transcription',
    method: 'POST',
    path: '/vid2txt',
    description: 'Transcribe video from YouTube/X/Twitch URL',
    contentType: 'json',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/vid2txt/price-calculation',
    inferenceType: 'video2text',
    params: [
      {
        name: 'video_url',
        label: 'Video URL',
        type: 'text',
        required: true,
        placeholder: 'https://youtube.com/watch?v=...',
        description: 'YouTube, X, or Twitch video URL',
      },
      modelSelectParam(),
      {
        name: 'include_ts',
        label: 'Include Timestamps',
        type: 'boolean',
        required: true,
        default: false,
      },
    ],
  },

  {
    id: 'videofile2txt',
    name: 'Video File to Text',
    group: 'transcription',
    method: 'POST',
    path: '/videofile2txt',
    description: 'Transcribe uploaded video file',
    contentType: 'multipart',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/videofile2txt/price-calculation',
    inferenceType: 'video_file2text',
    params: [
      {
        name: 'video',
        label: 'Video File',
        type: 'file',
        required: true,
        accept: 'video/*',
      },
      {
        name: 'include_ts',
        label: 'Include Timestamps',
        type: 'boolean',
        required: true,
        default: false,
      },
      modelSelectParam(),
    ],
  },

  {
    id: 'aud2txt',
    name: 'Audio URL to Text',
    group: 'transcription',
    method: 'POST',
    path: '/aud2txt',
    description: 'Transcribe audio from X/Twitter Spaces URL',
    contentType: 'json',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/aud2txt/price-calculation',
    inferenceType: 'audio2text',
    params: [
      {
        name: 'audio_url',
        label: 'Audio URL',
        type: 'text',
        required: true,
        placeholder: 'https://x.com/i/spaces/...',
        description: 'X/Twitter Spaces URL',
      },
      modelSelectParam(),
      {
        name: 'include_ts',
        label: 'Include Timestamps',
        type: 'boolean',
        required: true,
        default: false,
      },
    ],
  },

  {
    id: 'audiofile2txt',
    name: 'Audio File to Text',
    group: 'transcription',
    method: 'POST',
    path: '/audiofile2txt',
    description: 'Transcribe uploaded audio file',
    contentType: 'multipart',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/audiofile2txt/price-calculation',
    inferenceType: 'audio_file2text',
    params: [
      {
        name: 'audio',
        label: 'Audio File',
        type: 'file',
        required: true,
        accept: 'audio/*',
      },
      {
        name: 'include_ts',
        label: 'Include Timestamps',
        type: 'boolean',
        required: true,
        default: false,
      },
      modelSelectParam(),
    ],
  },

  // ── OCR ───────────────────────────────────────────────────
  {
    id: 'img2txt',
    name: 'Image to Text (OCR)',
    group: 'ocr',
    method: 'POST',
    path: '/img2txt',
    description: 'Extract text from images',
    contentType: 'multipart',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/img2txt/price-calculation',
    params: [
      {
        name: 'image',
        label: 'Image',
        type: 'file',
        required: true,
        accept: 'image/*',
      },
      modelSelectParam(),
      {
        name: 'language',
        label: 'Language',
        type: 'text',
        required: false,
        placeholder: 'auto',
        description: 'OCR language hint',
      },
    ],
  },

  // ── Image Utils ───────────────────────────────────────────
  {
    id: 'img-rmbg',
    name: 'Remove Background',
    group: 'image-utils',
    method: 'POST',
    path: '/img-rmbg',
    description: 'Remove image background',
    contentType: 'multipart',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/img-rmbg/price-calculation',
    params: [
      {
        name: 'image',
        label: 'Image',
        type: 'file',
        required: true,
        accept: 'image/*',
      },
      modelSelectParam(),
    ],
  },

  {
    id: 'img-upscale',
    name: 'Upscale Image',
    group: 'image-utils',
    method: 'POST',
    path: '/img-upscale',
    description: 'Upscale image resolution',
    contentType: 'multipart',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/img-upscale/price-calculation',
    params: [
      {
        name: 'image',
        label: 'Image',
        type: 'file',
        required: true,
        accept: 'image/*',
      },
      modelSelectParam(),
    ],
  },

  // ── Embeddings ────────────────────────────────────────────
  {
    id: 'txt2embedding',
    name: 'Text to Embedding',
    group: 'embeddings',
    method: 'POST',
    path: '/txt2embedding',
    description: 'Generate vector embeddings for RAG',
    contentType: 'json',
    isAsync: true,
    hasPriceCalc: true,
    priceCalcPath: '/txt2embedding/price-calculation',
    params: [
      {
        name: 'input',
        label: 'Input Text',
        type: 'textarea',
        required: true,
        placeholder: 'Text to embed...',
        supportsArray: true,
      },
      modelSelectParam(),
    ],
  },

  // ── Utility ───────────────────────────────────────────────
  {
    id: 'models',
    name: 'List Models',
    group: 'utility',
    method: 'GET',
    path: '/models',
    description: 'Get all available models with specifications',
    contentType: 'json',
    isAsync: false,
    hasPriceCalc: false,
    params: [],
  },

  {
    id: 'balance',
    name: 'Check Balance',
    group: 'utility',
    method: 'GET',
    path: '/balance',
    description: 'Check account credit balance',
    contentType: 'json',
    isAsync: false,
    hasPriceCalc: false,
    params: [],
  },

  {
    id: 'request-status',
    name: 'Get Job Result',
    group: 'utility',
    method: 'GET',
    path: '/request-status/{request_id}',
    description: 'Retrieve job status and results by request_id',
    contentType: 'json',
    isAsync: false,
    hasPriceCalc: false,
    params: [
      {
        name: 'request_id',
        label: 'Request ID',
        type: 'text',
        required: true,
        isPathParam: true,
        placeholder: 'c08a339c-73e5-4d67-a4d5-231302fbff9a',
        description: 'The request_id returned when job was submitted',
      },
    ],
  },
];

// Helper: get endpoints by group
export function getEndpointsByGroup(group: string): EndpointDefinition[] {
  return ENDPOINTS.filter(e => e.group === group);
}

// Helper: get endpoint by ID
export function getEndpointById(id: string): EndpointDefinition | undefined {
  return ENDPOINTS.find(e => e.id === id);
}
